baseURL = "https://qaware.github.io/"
languageCode = "en-us"
title = "QAware | Software Engineering Blog"
theme = "qaware-blog-theme"
author = "QAware GmbH"
copyright = "Copyright © 2020, QAware GmbH; all rights reserved."
paginate = 10

[params]
logo = "/images/qaware_logo.png"
kununu_name = "qaware"
twitter_handle = "qaware"
linkedin_company = "qaware-gmbh"
github_name = "qaware"
slideshare_name = "qaware"
youtube_channel = "UCmNf72xADnO57idipq9jvMg"
